services:
  app:
    build:
      context: ./Symfony
      dockerfile: ./dockerfile.yml
    container_name: symfony_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./Symfony:/app
      - /app/vendor
    depends_on:
      - db
    networks:
      symfony_network:
        aliases:
          - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      symfony_network:
        aliases:
          - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - symfony_network

volumes:
  db_data:

networks:
  symfony_network:
    driver: bridge
