-- CREATE TABLE users (
--                        id SERIAL PRIMARY KEY,
--                        username VARCHAR(255) NOT NULL,
--                        email VARCHAR(255) NOT NULL UNIQUE,
--                        password VARCHAR(255) NOT NULL,
--                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
--
-- INSERT INTO users (username, email) VALUES ('john_doe', 'john.doe@example.com', 'passpass');